# Generated by Django 3.2.6 on 2022-01-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_noti', models.CharField(choices=[('comment_answer', 'comment_answer'), ('question_comment', 'question_comment'), ('community_message', 'community_message'), ('question_edit', 'question_edit'), ('question_reopen_voted', 'Question ReOpen Voted'), ('question_suggested_edit', 'Question Suggested Edit'), ('NEW_ANSWER', 'New_Answer')], default='', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrivRepNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='#', null=True)),
                ('for_if', models.CharField(default='', max_length=30)),
                ('date_created_PrivNotify', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type_of_PrivNotify', models.CharField(choices=[('EDIT_GOT_APPROVED', 'Edit Approved'), ('ANSWER_ACCEPT_REP_P', 'Answer Accept Rep Plus'), ('BOUNTY_AWARDED_REP_P', 'Bounty Award Rep Plus'), ('MY_ANSWER_UPVOTE_REP_P', 'Answered Answer Upvote Rep Plus'), ('QUESTION_DOWNVOTE', 'Question DownVote'), ('MY_QUESTION_UPVOTE_REP_P', 'Asked Question Upvote Rep Plus'), ('Privilege_Earned', 'Privilege Earned'), ('BADGE_EARNED', 'Badge Earned')], default='', max_length=30)),
                ('missingReputation', models.IntegerField(blank=True, default=0, null=True)),
                ('privilegeURL', models.URLField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
