# Generated by Django 3.2.6 on 2022-01-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagbadge', '0002_tagbadge'),
    ]

    operations = [
    ]
